$.extend({
	login:function(){
		$(document).ready(function(){
			$('#table_login').on('click','button',function(){
				tmpurl=$('#form_login').attr('action');
				tmpdata='username='+$('#username').val()+'&userpassword='+$('#userpassword').val();
				$.ajx(tmpurl,tmpdata);
			});
		});
	}
});