<?php
//定义根路径
	$basedir=str_replace('\\','/',dirname(dirname(__FILE__))).'/';
	define(BASE_DIR,$basedir);
	unset($basedir);
//定义常数参数
	define(CFG_DIR,'cfg/');
	define(CFG_SLF,'self.cfg.php');
	define(INC_DIR,'inc/');
	define(INC_DB,'db.inc.php');
	define(CSS_DIR,'css/');
	define(CSS_FILE,'default.css');
	define(JS_DIR,'js/');
	define(JS_JQ,'jquery-1.11.3.min.js');
	define(JS_FUNC,'func.js');
	define(JS_LOGIN,'login.js');
	define(MDL_DIR,'mdl/');
	define(MDL_WEB,'web.mdl.php');
	define(MDL_LOGIN,'login.mdl.php');
	define(MDL_LOGOUT,'loginout.mdl.php');
	define(MDL_MENU,'menu.mdl.php');
	define(MDL_MAIN_VIEW,'main_view.mdl.php');
	define(MDL_HEAD,'head.mdl.php');
	define(MDL_FOOT,'foot.mdl.php');
	define(DB_NAME,ops_manager);
	define(DB_HOST,'127.0.0.1');
	define(DB_USER,'opsuser');
	define(DB_PASSWD,'opsuser_@liujin.1243.com');
//请自建self.cfg.php 定义BASE_URL
//加载页面
	require_once BASE_DIR.CFG_DIR.CFG_SLF;
?>
