<?php
//定义根路径
	$basedir=str_replace('\\','/',dirname(dirname(__FILE__))).'/';
	define(BASE_DIR,$basedir);
	unset($basedir);
//定义常数参数
	define(CFG_DIR,'cfg/');
	define(INC_DIR,'inc/');
	define(CSS_DIR,'css/');
	define(INC_IDX,'idx.inc.php');
	define(CFG_SLF,'self.cfg.php');
//加载页面
	require_once(BASE_DIR.CFG_DIR.CFG_SLF);
	require_once(BASE_DIR.INC_DIR.INC_IDX);
?>
